### PR TITLE
Fixes up the contributor acknowledgements in repo

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
# What is the feature?
* Adds authors and contributors to the repository

# How have you implemented the solution?
* using all_contributors GitHub action
* demarks between author and contributor in DESCRIPTION file
* Adds ORCIDs for everyone in DESCRIPTION

# Does the PR impact any other area of the project, maybe another repo?
* No, but a similar change was made to the .io site to add a list of all contributors, that is more extensive than what is provided in the DESCRIPTION.

### CODE REVIEW

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, thanks for putting this together. I'm totally sold on {allcontributors}. Did you run the commands in the PR locally such that you could share what the modified README looks like? If not I'll explore that myself.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA I did but have since deleted it. Let me know if you have trouble locally and need me to add it to this PR.

**Review by iantaylor-NOAA — CHANGES_REQUESTED** [review]
Thanks @kellijohnson-NOAA, the README looks good. However, the `alphabetical` argument caused me an error that I'm trying to help fix in https://github.com/ropensci/allcontributors/pull/53. 
I would either change to `alphabetical = FALSE` or wait until the problem subject to that PR is resolved.'

Second, I'm unclear on the system for ordering the authors and contributors in DESCRIPTION. Why not have them be alphabetical for everyone after the project lead?

**Comment by kellijohnson-NOAA** [comment]
Feel free to change alphabetical to whatever you would like to see or think is best for right now. Second, there is no ordering to the DESCRIPTION file. I just added ORCID's and middle initials to those entries that needed them. Feel free to alphabetize them if you think it should be that way.

**Comment by kellijohnson-NOAA** [comment]
The changes have been made, and the DESCRIPTION file is now in order by type of contributor and family name.

**Comment by iantaylor-NOAA** [comment]
Thanks @kellijohnson-NOAA. Sorry I got wrapped up in other stuff and didn't get back to the DESCRIPTION file in time.

**Pull request merged**
