### PR TITLE
46 feature module skeleton function created

### PR DESCRIPTION
**Pull request by ChristineStawitz-NOAA**
Thanks for opening a pull request (PR) to FIMS! Please describe the changes under the headings below. Please also go through the checklist below to ensure the appropriate steps have been taken during development. For smaller changes, feel free to skip steps that aren't relevant, but at least describe the feature under the "what is the feature".

# What is the feature?
A new R function `use_module` that creates a number of folders and .hpp files based on the templates in "inst/templates"

# How have you implemented the solution?
This uses the `usethis::use_template` function to copy over the .hpp template files, create the module_type (e.g. growth) folder and .hpp file, and create a module_name.hpp (e.g. EWAA) file as well as a module_type_base.hpp file.

# Does it impact any other area of the project?
No, this is an R function so it shouldn't impact any of the work in C++

# Does this change impact the model input or output?*
No

# How to test this change
I can't get the testthat test case working yet because it involves messing with the project directory structure, but you can manually test it by installing the package and running `use_module(".", module_type = "growth", module_name = "ewaa")`. I tested it with a dummy mortality function too.

# Developer pre-PR Checklist

Please do these steps locally for big changes. Note GitHub Actions does all of these checks automatically when pushing to the repository. Please see [code development section in the contributor guide](https://noaa-fims.github.io/collaborative_workflow/contributor-guidelines.html#code-development) for details.

- [ ] Run [cmake build and ctest locally](https://noaa-fims.github.io/collaborative_workflow/testing.html#c-unit-testing-and-benchmarking) and make sure the C++ tests pass
- [ ] Run `devtools::document()` locally and push changes to the remote feature branch
- [ ] Run `styler::style_pkg()` locally and push changes to remote feature branch. If there are many changes, please do this in a separate commit.
- [ ] Run `devtools::check()` locally and make sure the package can be compiled and R tests pass. If there are failing tests, run `devtools::test(filter = "file_name")` (where "test-file_name.R" is the testthat file containing failing tests) and edit code/tests to troubleshoot tests.
- [ ] Before opening the PR, make sure all the github actions are passing on the remote feature branch.
- [ ] Make sure this PR has an informative title.

### CODE REVIEW

**Comment by Andrea-Havron-NOAA** [comment]
This function will help developers initiate files needed for a new module.  Code is well written and will greatly improve the development experience. There are a few tasks that need to be addressed before merging into main. 

**devtools::check() warning**:

- The following [warning](https://github.com/NOAA-FIMS/FIMS/runs/6499012920?check_suite_focus=true#step:9:117) is reported from devtools::check():
  - `Warning:   '::' or ':::' import not declared from: 'usethis'`
It looks like this is caused by calling usethis::use_template on [line 47](https://github.com/NOAA-FIMS/FIMS/blob/9a238974fe6f88f0505319e3871a09f42a5be091/R/use_module.R#L47) of use_module.R. To fix this, usethis needs to be added to the DESCRIPTION file under Imports.
- @param global_equation is not used in the use_module() function and gets flagged on my local devtools::check()
  - ```checking Rd \usage sections ... WARNING
     Documented arguments not in \usage in documentation object 'use_module':
    'global_equation' 

**Documentation**:

- The function is not yet accessible from FIMS after install, however, because the NAMESPACE has not been updated with export(use_module). You will need to run devtools::document() or roxygen2::roxygenize() to update NAMESPACE and push changes. 
- It also looks like the @return and @examples fields in the use_module function documentation needs to be filled out. 

**Tests**:

- I was able to test the function using the recommended code above. There are a few funtions I wasn't able to access (create_local_packages, read_utf8, expect_error_free). The read_utf8 function comes from xfun, which should be added to Suggests in DESCRIPTION and loaded in the test using library(xfun). The functions create_local_packages() and expect_error_free look like they are associated with the usethis package, but I don't see them listed as functions when called using usethis::
- Do we need additional tests focused on testing error messages using testthat::expect_error?

Complete the following tasks:
- [ ] Add usethis to Imports in DESCRIPTION
- [ ] Add documentation to @return and @examples fields in use_module()
- [ ] Update NAMESPACE with `devtools::document()` or `roxygen2::roxygenize()` and push changes
- [ ] Add xfun and other libraries used to run tests to Suggests in DESCRIPTION
- [ ] Add additional error tests?

**Comment by ChristineStawitz-NOAA** [comment]
Updates to the `DESCRIPTION`, `NAMESPACE` and docs as requested! I did not include xfun since right now the test codes are commented out and I don't want to add dependencies to the package until we have some functional tests, but I will add it if I end up turning those test cases on in the future.

Thanks for your review + catching these issues!

**Comment by Andrea-Havron-NOAA** [comment]
I got the following error when running the use_module() example:

```
> use_module(system.file(package = 'FIMS'), module_name = "ewaa", module_type = "growth")
v Writing 'C:/Users/Andrea.Havron/Documents/github/NOAA-FIMS/FIMS/inst/include/population_dynamics/growth/functors/ewaa.hpp'
Error in file(path, open = file_mode, encoding = "utf-8") : 
  cannot open the connection
In addition: Warning message:
In file(path, open = file_mode, encoding = "utf-8") :
  cannot open file 'C:/Users/Andrea.Havron/Documents/github/NOAA-FIMS/FIMS/C:/Users/Andrea.Havron/Documents/github/NOAA-FIMS/FIMS/inst/include/population_dynamics/growth/functors/ewaa.hpp': Invalid argument
v Writing 'C:/Users/Andrea.Havron/Documents/github/NOAA-FIMS/FIMS/inst/include/population_dynamics/growth/functors/growth_base.hpp'
Error in file(path, open = file_mode, encoding = "utf-8") : 
  cannot open the connection
In addition: Warning message:
In file(path, open = file_mode, encoding = "utf-8") :
  cannot open file 'C:/Users/Andrea.Havron/Documents/github/NOAA-FIMS/FIMS/C:/Users/Andrea.Havron/Documents/github/NOAA-FIMS/FIMS/inst/include/population_dynamics/growth/functors/growth_base.hpp': Invalid argument
```

This error is being thrown by [line 50](https://github.com/NOAA-FIMS/FIMS/blob/3d6cb8654c84fe24fd9b1909ab110a877c0868e1/R/use_module.R#L50). The object subdir needs to be 'inst/include/population_dynamics' because the path here needs to be relative to the path of the template directory as per
```
> ?usethis::use_template
use_template(
  template,
  save_as = template,
  data = list(),
  ignore = FALSE,
  open = FALSE,
  package = "usethis"
)
Arguments
template	Path to template file relative to templates/ directory within package; see details.
...

```
The following works:
`use_module("inst", module_type = "growth", module_name = "ewaa")`

**Comment by ChristineStawitz-NOAA** [comment]
- [ ] add `on.exit` at the end since I'm using `setwd()`

**Comment by ChristineStawitz-NOAA** [comment]
hm @Bai-Li-NOAA I can run the test case locally when I do `testthat::test_file()` but it fails `devtools::check()` with the error: `Error in `setwd(subdir)`: cannot change working directory`

Do you know what is going on?

**Comment by Bai-Li-NOAA** [comment]
I tried a few other approaches, but could not fix it. We may be able to run it successfully through devtools::test(), but I can not get it work through devtools::test_coverage(). I suspect there are conflicts between working directory that is set by us which works locally and the default working directories used by devtools::test() and devtools::test_coverage() under GHA testing environment. Maybe we can comment out the test for now and add a help_wanted label for this issue?

**Comment by ChristineStawitz-NOAA** [comment]
Thanks for chekcing - I commented out so we can merge it in for now without a test case

**Review by Andrea-Havron-NOAA — APPROVED** [review]
Thanks for addressing recommended changes. It is noted that the unit test will be addressed in a separate issue. This PR is ready to merge into main.

**Pull request merged**
