### PR TITLE
Update DESCRIPTION

### PR DESCRIPTION
**Pull request by peterkuriyama-NOAA**
# What is the feature?

* 

# How have you implemented the solution?

# Does the PR impact any other area of the project?

# How to test this change

# Developer pre-PR checklist

- [x] I relied on GitHub actions to :test_tube: things for me while I sat on the :couch_and_lamp:.

### CODE REVIEW

**Comment by ChristineStawitz-NOAA** [comment]
thanks for adding yourself to the `DESCRIPTION` @peterkuriyama-NOAA ! I was wondering why you changed the R version to 4.0 or if this was done unintentionally by `usethis` or `devtools`?

**Comment by k-doering-NOAA** [comment]
We were reminded by looking at #361 that the R version listed as required on the readme was 4.0, although it is unclear where this came from...

**Comment by iantaylor-NOAA** [comment]
R 4.0 seems like a good idea in general regardless of origin. Surely none of us are using older versions nor have intention to test or support older versions.

**Comment by peterkuriyama-NOAA** [comment]
I edited the R version to match the readme. Happy to edit it to something
else though

**Review by ChristineStawitz-NOAA — APPROVED** [review]

**Pull request merged**
