### PR TITLE
removing mkObj from codebase

### PR DESCRIPTION
**Pull request by MOshima-PIFSC**
# What is the feature?

* Removed `mkObj()` from codebase because the function was no longer used

# How have you implemented the solution?

I removed the the script with the function (`io.R`) and ran `devtools::document()` to remove man/mkObj.Rd, and removed the function from the namespace. 

# Does the PR impact any other area of the project?

None

# How to test this change

I ran `devtools::check()` and the changes did not cause any errors.
# Developer pre-PR checklist

- [x] I relied on GitHub actions to :test_tube: things for me while I sat on the :couch_and_lamp:.

### CODE REVIEW

**Review by kellijohnson-NOAA — APPROVED** [review]
🥇

**Review by Andrea-Havron-NOAA — CHANGES_REQUESTED** [review]
move `@importFrom TMB MakeADFun` to R/FIMS-package.R

**Comment by MOshima-PIFSC** [comment]
@Andrea-Havron-NOAA I made the changes you requested and now it is passing all tests!

**Review by Andrea-Havron-NOAA — APPROVED** [review]

**Comment by Andrea-Havron-NOAA** [comment]
looks good!

**Pull request merged**
