### PR TITLE
install ninja via package manager instead of using packaged ninja action

### LINKED ISSUE #420: [Refactor]: warnings from node12 on gha
### Refactor request

the gtest github actions have warnings because node 12 is deprecated. We need to update the actions used within the workflows to the latest versions.

### Expected behavior

No warnings in the "annotations" section on the gha runs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
# What is the feature?
Update from using node12, which is deprecated on Github actions. resolves #420 

# How have you implemented the solution?
install ninja via package manager instead of using packaged ninja action

# Does the PR impact any other area of the project?
Just stops warnings on the run-googletest action.

# How to test this change
Look at the run-googletest github actions runs that this PR triggers and note that there are no warnings (no "annotations" section on the workflow run)

# Developer pre-PR checklist

- [x] I relied on GitHub actions to :test_tube: things for me while I sat on the :couch_and_lamp:.

### CODE REVIEW

**Comment by Andrea-Havron-NOAA** [comment]
Playing around with GitHub automatic review assignments - sorry about any confusion!

**Review by Bai-Li-NOAA — APPROVED** [review]

**Comment by Bai-Li-NOAA** [comment]
Thanks @k-doering-NOAA for updating the code to install Ninja. The code looks good to me. However, the run-googletest GHA failed when uploading test coverage to codecov. Do you know how to run failed GHA only? For some reason, I cannot find the option to run failed GHA again. I only see the "create status badge" option.

I have approved the code review but merging is still blocked due to the failed GHA.

**Comment by nathanvaughan-NOAA** [comment]
This doesn't help @Bai-Li-NOAA  but the rerun action and rerun only failed action options are missing now for me too so it's not just you??

**Comment by nathanvaughan-NOAA** [comment]
Also, the failed bash error holding this up seems to be happening a lot and somewhat at random. I had to rerun a bunch of the checks to get them all to pass even after merging into main last week. They failed randomly on both the Windows and Ubuntu tests. I don't know if this is something to do with our code or just a github/actions issue?

**Comment by k-doering-NOAA** [comment]
Hmm, I noticed I also don't have write permissions to FIMS anymore and that there was some changing of teams yesterday, so maybe that is why the "rerun job" button has disappeared for us? @Andrea-Havron-NOAA maybe you can help us figure out permissions issues?

As for the bash thing, I've been seeing what Nathan has - I think it will resolve itself and re-running should do the trick...

**Comment by k-doering-NOAA** [comment]
looks like I have write access now, thanks!

**Comment by k-doering-NOAA** [comment]
> Thanks @Andrea-Havron-NOAA, I am able to re-run GHA workflows now.
> 
> @k-doering-NOAA , maybe we can add extra steps to automatically retry an Action step on failure or timeout? See examples [here](https://github.com/marketplace/actions/retry-step).

Ooo cool! I didn't know that existed. Perhaps if the code cov issue keeps happening we can add it.

**Pull request merged**
