### PR TITLE
fix: bug fix Rcpp module loading

### PR DESCRIPTION
**Pull request by msupernaw**
Added to NAMESPACE:

useDynLib(FIMS, .registration=TRUE)
#required for module loading
importFrom(Rcpp, evalCpp)

required to load Rcpp module

*What is the feature?*
A brief title of this change.

*How have you implemented the solution?*
Describe the changes.

*Does it impact any other area of the project?*
Please describe which features are impacted by this change.

*Does this change impact the model input or output?*
Please describe any way this change impacts the model input or output.

*How to test this change*
Please include a test file and/or Github workflow.

### CODE REVIEW

**Comment by Andrea-Havron-NOAA** [comment]
The namespace will be overwritten during R build so we need to edit the Roxygen comments in the [R/io.R](https://github.com/NOAA-FIMS/FIMS/blob/bug-fix-module-load/R/io.R) file instead of namespace directly:

```
#' @useDynLilb FIMS, .registration = TRUE
#' importFrom Rcpp evalCpp
```

**Review by Andrea-Havron-NOAA — CHANGES_REQUESTED** [review]
GHA are failing due to issues that have been corrected in the main. Please merge in the main to this branch before the PR can be approved.

The namespace file will be overwritten on R build so the Roxygen comments in R/io.R need to be edited in addition to this change:
```
#' @useDynLib FIMS, .registration = TRUE
#' @importFrom Rcpp evalCpp
```

**Review by Andrea-Havron — APPROVED** [review]
Thanks for merging in main. Approving the pull request.

**Review by Andrea-Havron-NOAA — APPROVED** [review]
thanks for making necessary changes, ok to merge in

**Pull request merged**
