### PR TITLE
feat: adds weight-at-age data to input data frame

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
# What is the feature?

Adds weight-at-age to the data frame

# How have you implemented the solution?

As well as adding weight-at-age data to the input data frame,
this commit also uses a development branch of the {ASSAMC}
to run a single iteration of the Operating Model, and thus,
simplifies the code needed here by quite a bit.

Lines with 80 # are used to separate out major sections of the code.

# How to test this change

No tests are available yet and there are lots of TODO comments in the code that need to be looked at.

### CODE REVIEW

**Comment by ChristineStawitz-NOAA** [comment]
I see some checks are failing because of the TMB `isnan` bug which is fixed in main. I suggest you merge the latest main into these branches.

**Comment by kellijohnson-NOAA** [comment]
Thanks @ChristineStawitz-NOAA I just did
```
git fetch -a
git merge origin/main
git push origin sandbox-kj-make-dat
```
hopefully that was right?

**Comment by ChristineStawitz-NOAA** [comment]
Thanks - that fixed the `isnan` issue but now the tests are failing because it can't file the `ASSAMC` package

`Error in `loadNamespace(x)`: there is no package called ‘ASSAMC’`

**Comment by kellijohnson-NOAA** [comment]
Right, I think that we should move this script to data-raw rather than a test and save the data frame as a data object that is available to all users of FIMS/FIMS. @ChristineStawitz-NOAA do you have a preference for what we name the data frame as?

**Comment by ChristineStawitz-NOAA** [comment]
I am not familiar with data-raw, is this different than putting it in data/ ?  I do not have a strong preference as long as we stick to the R naming conventions, e.g. snake_case

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA thanks for adding it! feel free to add it to the sandbox-kd-make-dat branch when ready - but I can review the changes if you would like. Up to you!

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA I am wondering if we should forcefully remove the csv file so that the repository doesn't track it, leave it as is, or create a new branch with a more specific name and a cleaner commit history?

**Comment by kellijohnson-NOAA** [comment]
I condensed everything down to a single commit in 102-feat-data.

**Pull request closed without merging**
