### PR TITLE
add end ) to test-ewaa function

### PR DESCRIPTION
**Pull request by ChristineStawitz-NOAA**
Thanks for opening a pull request (PR) to FIMS! Please describe the changes under the headings below. Please also go through the checklist below to ensure the appropriate steps have been taken during development. For smaller changes, feel free to skip steps that aren't relevant, but at least describe the feature under the "what is the feature".

# What is the feature?
A brief title of this change.

# How have you implemented the solution?
Describe the changes.

# Does it impact any other area of the project?
Please describe which features are impacted by this change.

# Does this change impact the model input or output?*
Please describe any way this change impacts the model input or output.

# How to test this change
Please include a test file and/or Github workflow.

# Developer pre-PR Checklist

Please do these steps locally for big changes. Note GitHub Actions does all of these checks automatically when pushing to the repository. Please see [code development section in the contributor guide](https://noaa-fims.github.io/collaborative_workflow/contributor-guidelines.html#code-development) for details.

- [ ] Run [cmake build and ctest locally](https://noaa-fims.github.io/collaborative_workflow/testing.html#c-unit-testing-and-benchmarking) and make sure the C++ tests pass
- [ ] Run `devtools::document()` locally and push changes to the remote feature branch
- [ ] Run `styler::style_pkg()` locally and push changes to remote feature branch. If there are many changes, please do this in a separate commit.
- [ ] Run `devtools::check()` locally and make sure the package can be compiled and R tests pass. If there are failing tests, run `devtools::test(filter = "file_name")` (where "test-file_name.R" is the testthat file containing failing tests) and edit code/tests to troubleshoot tests.
- [ ] Before opening the PR, make sure all the github actions are passing on the remote feature branch.
- [ ] Make sure this PR has an informative title.

### CODE REVIEW

**Comment by ChristineStawitz-NOAA** [comment]
Thanks Bai - I think this should fix it but lets wait till the GHAs finish running to be sure

**Comment by Bai-Li-NOAA** [comment]
It seems that ewaa_growth$evaluate() will return 0 no matter what input value is in R. I am not sure whether [make_map](https://github.com/NOAA-FIMS/FIMS/blob/7f69d7763afec8e3be225932964b0e8fa5fa0083/inst/include/interface/rcpp/rcpp_objects/rcpp_growth.hpp#L61) is used when calling evaluate(). 

May be you can add a test that ages.size() != weights.size() as well. Right now, R does not return an error when length of age inputs does not equal to length of weight inputs.

**Comment by ChristineStawitz-NOAA** [comment]
yeah, I noticed that too. I am still trying to debug and will also add a check that the inputs match.

**Comment by ChristineStawitz-NOAA** [comment]
now I am getting some weird `Eigen` issues I can't figure out..I will probably need to look at it again next week so marking as draft

**Pull request closed without merging**
