### PR TITLE
fix Codespace fails to build, add rstudio option

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
# What is the feature?

* Fix codespaces build by including only pkgs that are dependencies
* Add Rstudio as an IDE option. To use, type `rserver` in the command line.more details: https://github.com/rocker-org/devcontainer-features/blob/main/src/rstudio-server/README.md

# How have you implemented the solution?

I think the inclusion of the cli and r lang packages was causing conflicts, which resulted in the codespace failing to build. I removed all packages that weren't dependencies of FIMS (and added some that are, but weren't listed) and was able to successfully build a codespace.

# Does the PR impact any other area of the project?

No

# How to test this change

Try building a codespace on this branch and see if it succeeds.

# Developer pre-PR checklist

- [x] I relied on GitHub actions to :test_tube: things for me while I sat on the :couch_and_lamp:.

### CODE REVIEW

**Comment by k-doering-NOAA** [comment]
@Andrea-Havron-NOAA I included you as a reviewer since you discovered this issue!

**Comment by k-doering-NOAA** [comment]
@Andrea-Havron-NOAA would you be able to review this? Or should someone else be assigned?

**Comment by Andrea-Havron-NOAA** [comment]
> @Andrea-Havron-NOAA would you be able to review this? Or should someone else be assigned?

I can review this!

**Review by ChristineStawitz-NOAA — APPROVED** [review]

**Review by Andrea-Havron-NOAA — APPROVED** [review]
My only suggestion would be to add more documentation on how to start the rstudio session. It was not clear to me that the `zsh` terminal was the correct one to use to call `rserver`. This could be added to the codespace documentation issue ([here](https://github.com/NOAA-FIMS/collaborative_workflow/issues/122)).

**Pull request merged**
