### PR TITLE
Gtest add integration

### PR DESCRIPTION
**Pull request by ChristineStawitz-NOAA**
Thanks for opening a pull request (PR) to FIMS! Please describe the changes under the headings below. Please also go through the checklist below to ensure the appropriate steps have been taken during development. For smaller changes, feel free to skip steps that aren't relevant, but at least describe the feature under the "what is the feature".

# What is the feature?
Merge in the integration test running via Google test

# How have you implemented the solution?
Made the integration test a header file + cpp that just calls the main `Run()` method
Add call to header file via integration_test_population.cpp in Google test
Compare numbers at age in json output file to what comes out of integrated test for population

# Does it impact any other area of the project?
I still get the same compile errors when I try to run the integrated test via command line

# Does this change impact the model input or output?*
no

# How to test this change
Please include a test file and/or Github workflow.

# Developer pre-PR Checklist

Please do these steps locally for big changes. Note GitHub Actions does all of these checks automatically when pushing to the repository. Please see [code development section in the contributor guide](https://noaa-fims.github.io/collaborative_workflow/contributor-guidelines.html#code-development) for details.

- [x] Run [cmake build and ctest locally](https://noaa-fims.github.io/collaborative_workflow/testing.html#c-unit-testing-and-benchmarking) and make sure the C++ tests pass
- [ ] Run `devtools::document()` locally and push changes to the remote feature branch
- [ ] Run `styler::style_pkg()` locally and push changes to remote feature branch. If there are many changes, please do this in a separate commit.
- [ ] Run `devtools::check()` locally and make sure the package can be compiled and R tests pass. If there are failing tests, run `devtools::test(filter = "file_name")` (where "test-file_name.R" is the testthat file containing failing tests) and edit code/tests to troubleshoot tests.
- [x] Before opening the PR, make sure all the github actions are passing on the remote feature branch.
- [x] Make sure this PR has an informative title.

### CODE REVIEW

**Comment by k-doering-NOAA** [comment]
@ChristineStawitz-NOAA and @msupernaw, I added changes so that we could pull R data files directly from the model comparison project and convert them to .json on the fly to use in gtest. This is now down within the gtest ghaction, and there is a utility function `FIMS::setup_and_run_gtest()` to setup for (i.e., get the input files need for the integration test), then run gtest from R.

Note that the integration test is not yet using the deterministic run, but we just have to change the path in `FIMS:::setup_gtest()` once the deterministic om run is ready.

**Comment by ChristineStawitz-NOAA** [comment]
Converted to a draft - will finalize when @JaneSullivan-NOAA has the final path of the deterministic run

**Comment by JaneSullivan-NOAA** [comment]
@ChristineStawitz-NOAA or @k-doering-NOAA: is this a situation where we are ok with all the failing tests? I think so, since it's only going into the integration-test branch not the main?

**Comment by k-doering-NOAA** [comment]
Good point, it looks like these tests are failing because FIMS can't be compiled...This also brings up the point that if FIMS can't be compiled, the gtest also fails (because it relies on a step of building the R package, which we could take out and use source() instead...

**Comment by ChristineStawitz-NOAA** [comment]
Yeah, I was thinking we would resolve the failing tests in integration-test before we merge into main. I fixed all the tests other than the integration tests locally in gtest, so we still need to fix the integration test (plan to do in the integration-test branch) and R cmd check (can do that in this branch or integration-test)

**Comment by JaneSullivan-NOAA** [comment]
@ChristineStawitz-NOAA - sorry I've been behind at work... Is this PR ready for review?

**Comment by ChristineStawitz-NOAA** [comment]
Sorry @JaneSullivan-NOAA I marked it as ready because I thought it was but now I get errors again when I run it locally! Maybe I forgot to commit? I will mark as draft again till I fix it.

**Comment by JaneSullivan-NOAA** [comment]
No worries @ChristineStawitz-NOAA, just let me know when it's ready for review.

**Comment by ChristineStawitz-NOAA** [comment]
OK @JaneSullivan-NOAA and @msupernaw this is ready for review - only the integration gtest test should still be failing.

**Review by msupernaw — APPROVED** [review]
looks good!

**Comment by ChristineStawitz-NOAA** [comment]
OK it is compiling now on the local machine! I changed the ages vector to `std::vector<double>` in Population but it was `std::vector<T>` in Information. I also got rid of some of the warnings by converting `int`s to `size_t`s

**Pull request merged**
